# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/brillouinview/gui/ui/calibration_fit_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalibrationFitWindow(object):
    def setupUi(self, CalibrationFitWindow):
        CalibrationFitWindow.setObjectName("CalibrationFitWindow")
        CalibrationFitWindow.resize(1194, 682)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CalibrationFitWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left = QtWidgets.QVBoxLayout()
        self.left.setContentsMargins(-1, 0, -1, -1)
        self.left.setObjectName("left")
        self.fit_plot = PlotWidget(CalibrationFitWindow)
        self.fit_plot.setMinimumSize(QtCore.QSize(0, 400))
        self.fit_plot.setObjectName("fit_plot")
        self.left.addWidget(self.fit_plot)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(CalibrationFitWindow)
        self.tableWidget.setMinimumSize(QtCore.QSize(750, 0))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(CalibrationFitWindow)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.le_used_function = QtWidgets.QLineEdit(CalibrationFitWindow)
        self.le_used_function.setMaximumSize(QtCore.QSize(500, 16777215))
        self.le_used_function.setAlignment(QtCore.Qt.AlignCenter)
        self.le_used_function.setReadOnly(True)
        self.le_used_function.setObjectName("le_used_function")
        self.verticalLayout_2.addWidget(self.le_used_function)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_cancel_calfit = QtWidgets.QPushButton(CalibrationFitWindow)
        self.button_cancel_calfit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.button_cancel_calfit.setObjectName("button_cancel_calfit")
        self.verticalLayout.addWidget(self.button_cancel_calfit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.button_accept_calfit = QtWidgets.QPushButton(CalibrationFitWindow)
        self.button_accept_calfit.setObjectName("button_accept_calfit")
        self.verticalLayout.addWidget(self.button_accept_calfit)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.pushButton_2 = QtWidgets.QPushButton(CalibrationFitWindow)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.pushButton_4 = QtWidgets.QPushButton(CalibrationFitWindow)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.left.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.left)

        self.retranslateUi(CalibrationFitWindow)
        QtCore.QMetaObject.connectSlotsByName(CalibrationFitWindow)

    def retranslateUi(self, CalibrationFitWindow):
        _translate = QtCore.QCoreApplication.translate
        CalibrationFitWindow.setWindowTitle(_translate("CalibrationFitWindow", "Calibration Fit Window"))
        self.label.setText(_translate("CalibrationFitWindow", "Used function"))
        self.button_cancel_calfit.setToolTip(_translate("CalibrationFitWindow", "Cancel the fit and return to the main window"))
        self.button_cancel_calfit.setText(_translate("CalibrationFitWindow", "Cancel"))
        self.button_accept_calfit.setToolTip(_translate("CalibrationFitWindow", "<html><head/><body><p>Accept the presented fit and return to the main window</p></body></html>"))
        self.button_accept_calfit.setText(_translate("CalibrationFitWindow", "Accept Fit"))
        self.pushButton_2.setToolTip(_translate("CalibrationFitWindow", "Adjust the starting parameters of the fit in case the result is not satisfacory"))
        self.pushButton_2.setText(_translate("CalibrationFitWindow", "Adjust starting Parameters"))
        self.pushButton_4.setToolTip(_translate("CalibrationFitWindow", "<html><head/><body><p>Save a Screenshot of the calibration fit</p></body></html>"))
        self.pushButton_4.setText(_translate("CalibrationFitWindow", "Save Screenshot"))
from pyqtgraph import PlotWidget
