# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/brillouinview/gui/ui/welcome_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Prequel_Dialog(object):
    def setupUi(self, Prequel_Dialog):
        Prequel_Dialog.setObjectName("Prequel_Dialog")
        Prequel_Dialog.resize(439, 264)
        self.verticalLayout = QtWidgets.QVBoxLayout(Prequel_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(Prequel_Dialog)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.button_new_dac = QtWidgets.QPushButton(Prequel_Dialog)
        self.button_new_dac.setObjectName("button_new_dac")
        self.verticalLayout.addWidget(self.button_new_dac)
        self.button_load_dac = QtWidgets.QPushButton(Prequel_Dialog)
        self.button_load_dac.setEnabled(False)
        self.button_load_dac.setObjectName("button_load_dac")
        self.verticalLayout.addWidget(self.button_load_dac)
        self.button_load_experiment = QtWidgets.QPushButton(Prequel_Dialog)
        self.button_load_experiment.setEnabled(True)
        self.button_load_experiment.setObjectName("button_load_experiment")
        self.verticalLayout.addWidget(self.button_load_experiment)
        self.button_read_manual = QtWidgets.QPushButton(Prequel_Dialog)
        self.button_read_manual.setEnabled(False)
        self.button_read_manual.setObjectName("button_read_manual")
        self.verticalLayout.addWidget(self.button_read_manual)

        self.retranslateUi(Prequel_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Prequel_Dialog)

    def retranslateUi(self, Prequel_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Prequel_Dialog.setWindowTitle(_translate("Prequel_Dialog", "Welcome to BrillouinView 1.0.0"))
        self.textBrowser.setHtml(_translate("Prequel_Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Sans\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Welcome to BrillouinView 1.0.0 </span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Your options are :</p></body></html>"))
        self.button_new_dac.setText(_translate("Prequel_Dialog", "Start with a new DAC"))
        self.button_load_dac.setText(_translate("Prequel_Dialog", "Load a DAC and add a new experiment"))
        self.button_load_experiment.setText(_translate("Prequel_Dialog", "Load an existing experiment"))
        self.button_read_manual.setText(_translate("Prequel_Dialog", "Read the Manual"))
